input_features:
    -
        name: Text
        type: text
        level: word
        encoder: parallel_cnn

output_features:
    -
        name: Polarity
        type: category

hyperopt:
  goal: maximize
  output_feature: Polarity
  metric: accuracy
  split: test
